# Agent/Lane Configuration
# Single source of truth for all agent and lane definitions
#
# This file defines all available agents in the system. When adding a new agent:
# 1. Add entry here with lane name, class_name, and description
# 2. Create the agent class in app/services/agents/
# 3. That's it! All validations, routing, and registry lookups use this file
#
# Fields:
#   class_name: Full class name of the agent (e.g., "Agents::InfoAgent")
#   description: Human-readable description for LLM routing prompts
#   is_default: (optional) Set to true for the default lane (only one allowed)

agents:
  info:
    class_name: "Agents::InfoAgent"
    description: "General business information (hours, location, menu, services, FAQs)"
    is_default: true

  product:
    class_name: "Agents::ProductAgent"
    description: "Product-specific questions (details, attributes, categories, availability, comparisons)"

  commerce:
    class_name: "Agents::CommerceAgent"
    description: "Shopping and transactions (browse products, add to cart, checkout, order tracking)"

  support:
    class_name: "Agents::SupportAgent"
    description: "Customer service issues (refunds, complaints, order problems, account help)"
